site_name: Profy App Documentation
theme: 
  name: material
  features:
    # - navigation.sections
    # - navigation.instant
    - toc.integrate
    - navigation.instant
    - navigation.expand
    # - navigation.top
    # - search.suggest
    # - search.highlight
    # - content.tabs.link
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: purple
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: purple
      accent: lime
extra_css:
  - stylesheets/extra.css
plugins:
   - glightbox
# To hide logo
# extra:
#   generator: false


